--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    lead_source text,
    -- Which ad / video / offer / magnet / form brought them in (whitelisted
    -- keys - see functions/_shared/attribution.ts). First-touch wins on merge.
    attribution jsonb not null default '{}'::jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    commission_rate_override numeric(5,4)
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    stripe_account_id text,
    stripe_account_status text,
    onboarding_completed_at timestamp with time zone
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

create table public.deal_payouts (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    sales_id bigint not null,
    amount_cents bigint not null default 0,
    commission_rate numeric(5,4) not null default 0.10,
    status text not null default 'pending',
    notes text,
    created_at timestamp with time zone not null default now(),
    approved_at timestamp with time zone,
    paid_at timestamp with time zone,
    stripe_transfer_id text,
    constraint deal_payouts_status_check check (status in ('pending','approved','paid','void'))
);

create table public.community_posts (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    title text not null,
    body text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.community_comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    sales_id bigint not null,
    body text not null,
    created_at timestamp with time zone not null default now()
);

create table public.notifications (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    type text not null,
    payload jsonb not null default '{}'::jsonb,
    read_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint notifications_type_check check (
      type in ('comment_on_post', 'lead_assigned', 'payout_approved', 'payout_paid', 'booking_created', 'agent_handoff', 'call_due', 'lead_replied')
    )
);

create table public.rep_availability (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    day_of_week smallint not null,
    start_time time not null,
    end_time time not null,
    created_at timestamp with time zone not null default now(),
    constraint rep_availability_day_check check (day_of_week between 0 and 6),
    constraint rep_availability_time_check check (end_time > start_time)
);

create table public.bookings (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    contact_id bigint,
    scheduled_for timestamp with time zone not null,
    duration_minutes smallint not null default 30,
    notes text,
    status text not null default 'scheduled',
    created_at timestamp with time zone not null default now(),
    constraint bookings_status_check check (status in ('scheduled', 'completed', 'canceled', 'no_show'))
);

-- Funnel automation: deferred SMS/task queue drained by the dispatch_tasks edge
-- function (pg_cron every minute). Reuses contacts/deals as the source of truth.
create table public.scheduled_tasks (
    id bigint generated by default as identity primary key,
    deal_id bigint,
    contact_id bigint,
    task_type text not null,
    payload jsonb not null default '{}'::jsonb,
    run_at timestamp with time zone not null,
    status text not null default 'pending',
    attempts smallint not null default 0,
    last_error text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint scheduled_tasks_status_check check (status in ('pending', 'processing', 'sent', 'failed', 'canceled'))
);

-- SMS opt-out list (STOP / manual). The dispatcher cancels any task to a
-- suppressed phone; the inbound handler adds rows on STOP.
create table public.sms_suppressions (
    id bigint generated by default as identity primary key,
    phone text not null,
    reason text not null default 'stop',
    contact_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint sms_suppressions_phone_unique unique (phone)
);

-- Email opt-out list — the email twin of sms_suppressions. Makes the drip
-- footer's 'reply "stop" and I won't email again' machine-enforced: the
-- dispatcher checks it before every email send; quo_inbound STOP and the Gmail
-- reply scan write to it.
create table public.email_suppressions (
    id bigint generated by default as identity primary key,
    email text not null,
    reason text not null default 'stop',
    contact_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint email_suppressions_email_unique unique (email)
);

-- Machine-readable transcript of the AI sales agent's SMS conversation with a
-- lead. Separate from contact_notes (which stays the human-facing timeline) so
-- the agent can rebuild context reliably.
create table public.agent_messages (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    deal_id bigint,
    direction text not null,
    body text not null,
    created_at timestamp with time zone not null default now(),
    constraint agent_messages_direction_check check (direction in ('inbound', 'outbound'))
);

-- Persisted sales calls (OpenPhone webhook via quo_call_events): one row per
-- call, upserted by openphone_call_id, with recording + transcript when the
-- plan provides them.
create table public.call_logs (
    id bigint generated by default as identity primary key,
    contact_id bigint,
    phone_number_id text,
    participant text,
    direction text,
    status text,
    duration integer,
    recording_url text,
    openphone_call_id text,
    created_at timestamp with time zone not null default now(),
    completed_at timestamp with time zone,
    sales_id bigint,
    transcript jsonb,
    summary text
);

create unique index call_logs_openphone_call_id_key
    on public.call_logs (openphone_call_id)
    where openphone_call_id is not null;
create index call_logs_contact_id_created_idx
    on public.call_logs (contact_id, created_at desc);

-- Fast lookup of the open double-dial call queue (dashboard CallQueueWidget).
create index tasks_open_call_idx
    on public.tasks (due_date)
    where done_date is null and type = 'call';

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.deal_payouts
    add constraint deal_payouts_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_payouts
    add constraint deal_payouts_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index deal_payouts_sales_id_idx on public.deal_payouts using btree (sales_id);
create index deal_payouts_deal_id_idx on public.deal_payouts using btree (deal_id);
create unique index deal_payouts_unique_per_deal on public.deal_payouts using btree (deal_id) where status != 'void';

alter table public.community_posts
    add constraint community_posts_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.community_comments
    add constraint community_comments_post_id_fkey foreign key (post_id) references public.community_posts(id) on update cascade on delete cascade;

alter table public.community_comments
    add constraint community_comments_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

create index community_posts_sales_id_idx on public.community_posts using btree (sales_id);
create index community_comments_post_id_idx on public.community_comments using btree (post_id);
create index community_comments_sales_id_idx on public.community_comments using btree (sales_id);

alter table public.notifications
    add constraint notifications_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

create index notifications_sales_id_unread_idx on public.notifications using btree (sales_id, read_at) where read_at is null;
create index notifications_sales_id_created_at_idx on public.notifications using btree (sales_id, created_at desc);

alter table public.rep_availability
    add constraint rep_availability_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.bookings
    add constraint bookings_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.bookings
    add constraint bookings_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

create index rep_availability_sales_id_idx on public.rep_availability using btree (sales_id);
create index bookings_sales_id_scheduled_for_idx on public.bookings using btree (sales_id, scheduled_for);
create index bookings_contact_id_idx on public.bookings using btree (contact_id);

alter table public.scheduled_tasks
    add constraint scheduled_tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.scheduled_tasks
    add constraint scheduled_tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.sms_suppressions
    add constraint sms_suppressions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

alter table public.email_suppressions
    add constraint email_suppressions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

-- Partial index over due, unsent work — the dispatcher's hot path.
create index scheduled_tasks_due_idx on public.scheduled_tasks using btree (run_at) where status = 'pending';
create index scheduled_tasks_deal_id_idx on public.scheduled_tasks using btree (deal_id);
create index scheduled_tasks_contact_id_idx on public.scheduled_tasks using btree (contact_id);

alter table public.agent_messages
    add constraint agent_messages_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.agent_messages
    add constraint agent_messages_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete set null;

create index agent_messages_contact_id_created_idx on public.agent_messages using btree (contact_id, created_at);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
