-- Persist sales calls + transcripts (voice-memo build: "we need transcripts of
-- all the calls").
--
-- call_logs already exists on prod (created directly via the dashboard, never
-- committed - a known ghost migration), so this file both brings the table
-- into git for fresh environments AND adds the transcript columns.
create table if not exists public.call_logs (
    id bigint generated by default as identity primary key,
    contact_id bigint,
    phone_number_id text,
    participant text,
    direction text,
    status text,
    duration integer,
    recording_url text,
    openphone_call_id text,
    created_at timestamp with time zone not null default now(),
    completed_at timestamp with time zone,
    sales_id bigint
);

alter table public.call_logs enable row level security;

-- Transcript payload from OpenPhone (dialogue segments) + a short summary line.
alter table public.call_logs add column if not exists transcript jsonb;
alter table public.call_logs add column if not exists summary text;

-- Dedupe key for webhook retries / multi-event upserts (call.completed then
-- call.transcript.completed both target the same row).
create unique index if not exists call_logs_openphone_call_id_key
  on public.call_logs (openphone_call_id)
  where openphone_call_id is not null;

create index if not exists call_logs_contact_id_created_idx
  on public.call_logs (contact_id, created_at desc);

-- Reps read call history team-wide (calls are shared sales activity, like the
-- /calls page). Writes stay service-role only (the quo_call_events webhook).
drop policy if exists "Call logs select for authenticated" on public.call_logs;
create policy "Call logs select for authenticated" on public.call_logs
  for select to authenticated
  using (true);
