
  create table "public"."community_comments" (
    "id" bigint generated by default as identity not null,
    "post_id" bigint not null,
    "sales_id" bigint not null,
    "body" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."community_comments" enable row level security;


  create table "public"."community_posts" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "title" text not null,
    "body" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."community_posts" enable row level security;

CREATE UNIQUE INDEX community_comments_pkey ON public.community_comments USING btree (id);

CREATE INDEX community_comments_post_id_idx ON public.community_comments USING btree (post_id);

CREATE INDEX community_comments_sales_id_idx ON public.community_comments USING btree (sales_id);

CREATE UNIQUE INDEX community_posts_pkey ON public.community_posts USING btree (id);

CREATE INDEX community_posts_sales_id_idx ON public.community_posts USING btree (sales_id);

alter table "public"."community_comments" add constraint "community_comments_pkey" PRIMARY KEY using index "community_comments_pkey";

alter table "public"."community_posts" add constraint "community_posts_pkey" PRIMARY KEY using index "community_posts_pkey";

alter table "public"."community_comments" add constraint "community_comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.community_posts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."community_comments" validate constraint "community_comments_post_id_fkey";

alter table "public"."community_comments" add constraint "community_comments_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."community_comments" validate constraint "community_comments_sales_id_fkey";

alter table "public"."community_posts" add constraint "community_posts_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."community_posts" validate constraint "community_posts_sales_id_fkey";

grant delete on table "public"."community_comments" to "anon";

grant insert on table "public"."community_comments" to "anon";

grant references on table "public"."community_comments" to "anon";

grant select on table "public"."community_comments" to "anon";

grant trigger on table "public"."community_comments" to "anon";

grant truncate on table "public"."community_comments" to "anon";

grant update on table "public"."community_comments" to "anon";

grant delete on table "public"."community_comments" to "authenticated";

grant insert on table "public"."community_comments" to "authenticated";

grant references on table "public"."community_comments" to "authenticated";

grant select on table "public"."community_comments" to "authenticated";

grant trigger on table "public"."community_comments" to "authenticated";

grant truncate on table "public"."community_comments" to "authenticated";

grant update on table "public"."community_comments" to "authenticated";

grant delete on table "public"."community_comments" to "service_role";

grant insert on table "public"."community_comments" to "service_role";

grant references on table "public"."community_comments" to "service_role";

grant select on table "public"."community_comments" to "service_role";

grant trigger on table "public"."community_comments" to "service_role";

grant truncate on table "public"."community_comments" to "service_role";

grant update on table "public"."community_comments" to "service_role";

grant delete on table "public"."community_posts" to "anon";

grant insert on table "public"."community_posts" to "anon";

grant references on table "public"."community_posts" to "anon";

grant select on table "public"."community_posts" to "anon";

grant trigger on table "public"."community_posts" to "anon";

grant truncate on table "public"."community_posts" to "anon";

grant update on table "public"."community_posts" to "anon";

grant delete on table "public"."community_posts" to "authenticated";

grant insert on table "public"."community_posts" to "authenticated";

grant references on table "public"."community_posts" to "authenticated";

grant select on table "public"."community_posts" to "authenticated";

grant trigger on table "public"."community_posts" to "authenticated";

grant truncate on table "public"."community_posts" to "authenticated";

grant update on table "public"."community_posts" to "authenticated";

grant delete on table "public"."community_posts" to "service_role";

grant insert on table "public"."community_posts" to "service_role";

grant references on table "public"."community_posts" to "service_role";

grant select on table "public"."community_posts" to "service_role";

grant trigger on table "public"."community_posts" to "service_role";

grant truncate on table "public"."community_posts" to "service_role";

grant update on table "public"."community_posts" to "service_role";


  create policy "Community comments delete author or admin"
  on "public"."community_comments"
  as permissive
  for delete
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));



  create policy "Community comments insert as self"
  on "public"."community_comments"
  as permissive
  for insert
  to authenticated
with check (((sales_id IS NULL) OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid()))) OR public.is_admin()));



  create policy "Community comments read all"
  on "public"."community_comments"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Community comments update author or admin"
  on "public"."community_comments"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))))
with check ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));



  create policy "Community posts delete author or admin"
  on "public"."community_posts"
  as permissive
  for delete
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));



  create policy "Community posts insert as self"
  on "public"."community_posts"
  as permissive
  for insert
  to authenticated
with check (((sales_id IS NULL) OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid()))) OR public.is_admin()));



  create policy "Community posts read all"
  on "public"."community_posts"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Community posts update author or admin"
  on "public"."community_posts"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))))
with check ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));


CREATE TRIGGER set_community_comment_sales_id_trigger BEFORE INSERT ON public.community_comments FOR EACH ROW EXECUTE FUNCTION public.set_sales_id_default();

CREATE TRIGGER set_community_post_sales_id_trigger BEFORE INSERT ON public.community_posts FOR EACH ROW EXECUTE FUNCTION public.set_sales_id_default();


