
  create table "public"."deal_payouts" (
    "id" bigint generated by default as identity not null,
    "deal_id" bigint not null,
    "sales_id" bigint not null,
    "amount_cents" bigint not null default 0,
    "commission_rate" numeric(5,4) not null default 0.10,
    "status" text not null default 'pending'::text,
    "notes" text,
    "created_at" timestamp with time zone not null default now(),
    "approved_at" timestamp with time zone,
    "paid_at" timestamp with time zone
      );


alter table "public"."deal_payouts" enable row level security;

CREATE INDEX deal_payouts_deal_id_idx ON public.deal_payouts USING btree (deal_id);

CREATE UNIQUE INDEX deal_payouts_pkey ON public.deal_payouts USING btree (id);

CREATE INDEX deal_payouts_sales_id_idx ON public.deal_payouts USING btree (sales_id);

CREATE UNIQUE INDEX deal_payouts_unique_per_deal ON public.deal_payouts USING btree (deal_id) WHERE (status <> 'void'::text);

alter table "public"."deal_payouts" add constraint "deal_payouts_pkey" PRIMARY KEY using index "deal_payouts_pkey";

alter table "public"."deal_payouts" add constraint "deal_payouts_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."deal_payouts" validate constraint "deal_payouts_deal_id_fkey";

alter table "public"."deal_payouts" add constraint "deal_payouts_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."deal_payouts" validate constraint "deal_payouts_sales_id_fkey";

alter table "public"."deal_payouts" add constraint "deal_payouts_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'paid'::text, 'void'::text]))) not valid;

alter table "public"."deal_payouts" validate constraint "deal_payouts_status_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_deal_won_payout()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  rate numeric(5,4);
  amount_cents bigint;
begin
  -- Only act when the deal just transitioned into stage 'won'.
  if NEW.stage is distinct from 'won' then
    return NEW;
  end if;

  if TG_OP = 'UPDATE' and OLD.stage = 'won' then
    -- Already won previously; do nothing.
    return NEW;
  end if;

  -- No rep on the deal — skip silently.
  if NEW.sales_id is null then
    return NEW;
  end if;

  -- Resolve commission rate from configuration.config.payouts.default_rate,
  -- defaulting to 10%.
  select coalesce(
    nullif(((c.config -> 'payouts' ->> 'default_rate'))::numeric, 0),
    0.10
  ) into rate
  from public.configuration c
  where c.id = 1;
  if rate is null then
    rate := 0.10;
  end if;

  amount_cents := round(coalesce(NEW.amount, 0) * rate * 100);

  -- Create the payout row. Unique index on deal_id (where status != 'void')
  -- protects against double-creates on rapid re-saves.
  insert into public.deal_payouts (deal_id, sales_id, amount_cents, commission_rate, status)
  values (NEW.id, NEW.sales_id, amount_cents, rate, 'pending')
  on conflict do nothing;

  return NEW;
end;
$function$
;

grant delete on table "public"."deal_payouts" to "anon";

grant insert on table "public"."deal_payouts" to "anon";

grant references on table "public"."deal_payouts" to "anon";

grant select on table "public"."deal_payouts" to "anon";

grant trigger on table "public"."deal_payouts" to "anon";

grant truncate on table "public"."deal_payouts" to "anon";

grant update on table "public"."deal_payouts" to "anon";

grant delete on table "public"."deal_payouts" to "authenticated";

grant insert on table "public"."deal_payouts" to "authenticated";

grant references on table "public"."deal_payouts" to "authenticated";

grant select on table "public"."deal_payouts" to "authenticated";

grant trigger on table "public"."deal_payouts" to "authenticated";

grant truncate on table "public"."deal_payouts" to "authenticated";

grant update on table "public"."deal_payouts" to "authenticated";

grant delete on table "public"."deal_payouts" to "service_role";

grant insert on table "public"."deal_payouts" to "service_role";

grant references on table "public"."deal_payouts" to "service_role";

grant select on table "public"."deal_payouts" to "service_role";

grant trigger on table "public"."deal_payouts" to "service_role";

grant truncate on table "public"."deal_payouts" to "service_role";

grant update on table "public"."deal_payouts" to "service_role";


  create policy "Payouts delete for admins"
  on "public"."deal_payouts"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Payouts insert for admins"
  on "public"."deal_payouts"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "Payouts select for owner or admin"
  on "public"."deal_payouts"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));



  create policy "Payouts update for admins"
  on "public"."deal_payouts"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());


CREATE TRIGGER deal_won_payout_trigger AFTER INSERT OR UPDATE OF stage ON public.deals FOR EACH ROW EXECUTE FUNCTION public.handle_deal_won_payout();


