alter table "public"."notifications" drop constraint "notifications_type_check";


  create table "public"."bookings" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "contact_id" bigint,
    "scheduled_for" timestamp with time zone not null,
    "duration_minutes" smallint not null default 30,
    "notes" text,
    "status" text not null default 'scheduled'::text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."bookings" enable row level security;


  create table "public"."rep_availability" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "day_of_week" smallint not null,
    "start_time" time without time zone not null,
    "end_time" time without time zone not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."rep_availability" enable row level security;

CREATE INDEX bookings_contact_id_idx ON public.bookings USING btree (contact_id);

CREATE UNIQUE INDEX bookings_pkey ON public.bookings USING btree (id);

CREATE INDEX bookings_sales_id_scheduled_for_idx ON public.bookings USING btree (sales_id, scheduled_for);

CREATE UNIQUE INDEX rep_availability_pkey ON public.rep_availability USING btree (id);

CREATE INDEX rep_availability_sales_id_idx ON public.rep_availability USING btree (sales_id);

alter table "public"."bookings" add constraint "bookings_pkey" PRIMARY KEY using index "bookings_pkey";

alter table "public"."rep_availability" add constraint "rep_availability_pkey" PRIMARY KEY using index "rep_availability_pkey";

alter table "public"."bookings" add constraint "bookings_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."bookings" validate constraint "bookings_contact_id_fkey";

alter table "public"."bookings" add constraint "bookings_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."bookings" validate constraint "bookings_sales_id_fkey";

alter table "public"."bookings" add constraint "bookings_status_check" CHECK ((status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'canceled'::text, 'no_show'::text]))) not valid;

alter table "public"."bookings" validate constraint "bookings_status_check";

alter table "public"."rep_availability" add constraint "rep_availability_day_check" CHECK (((day_of_week >= 0) AND (day_of_week <= 6))) not valid;

alter table "public"."rep_availability" validate constraint "rep_availability_day_check";

alter table "public"."rep_availability" add constraint "rep_availability_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."rep_availability" validate constraint "rep_availability_sales_id_fkey";

alter table "public"."rep_availability" add constraint "rep_availability_time_check" CHECK ((end_time > start_time)) not valid;

alter table "public"."rep_availability" validate constraint "rep_availability_time_check";

alter table "public"."notifications" add constraint "notifications_type_check" CHECK ((type = ANY (ARRAY['comment_on_post'::text, 'lead_assigned'::text, 'payout_approved'::text, 'payout_paid'::text, 'booking_created'::text]))) not valid;

alter table "public"."notifications" validate constraint "notifications_type_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.notify_on_booking_created()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  notif_id bigint;
  notif_payload jsonb;
  contact_first text;
  contact_last text;
begin
  if NEW.contact_id is not null then
    select first_name, last_name into contact_first, contact_last
    from public.contacts where id = NEW.contact_id;
  end if;

  notif_payload := jsonb_build_object(
    'booking_id', NEW.id,
    'contact_id', NEW.contact_id,
    'first_name', contact_first,
    'last_name', contact_last,
    'scheduled_for', NEW.scheduled_for,
    'duration_minutes', NEW.duration_minutes
  );

  insert into public.notifications (sales_id, type, payload)
  values (NEW.sales_id, 'booking_created', notif_payload)
  returning id into notif_id;

  perform public.send_notification_email(notif_id, NEW.sales_id, 'booking_created', notif_payload);
  return NEW;
end;
$function$
;

grant delete on table "public"."bookings" to "anon";

grant insert on table "public"."bookings" to "anon";

grant references on table "public"."bookings" to "anon";

grant select on table "public"."bookings" to "anon";

grant trigger on table "public"."bookings" to "anon";

grant truncate on table "public"."bookings" to "anon";

grant update on table "public"."bookings" to "anon";

grant delete on table "public"."bookings" to "authenticated";

grant insert on table "public"."bookings" to "authenticated";

grant references on table "public"."bookings" to "authenticated";

grant select on table "public"."bookings" to "authenticated";

grant trigger on table "public"."bookings" to "authenticated";

grant truncate on table "public"."bookings" to "authenticated";

grant update on table "public"."bookings" to "authenticated";

grant delete on table "public"."bookings" to "service_role";

grant insert on table "public"."bookings" to "service_role";

grant references on table "public"."bookings" to "service_role";

grant select on table "public"."bookings" to "service_role";

grant trigger on table "public"."bookings" to "service_role";

grant truncate on table "public"."bookings" to "service_role";

grant update on table "public"."bookings" to "service_role";

grant delete on table "public"."rep_availability" to "anon";

grant insert on table "public"."rep_availability" to "anon";

grant references on table "public"."rep_availability" to "anon";

grant select on table "public"."rep_availability" to "anon";

grant trigger on table "public"."rep_availability" to "anon";

grant truncate on table "public"."rep_availability" to "anon";

grant update on table "public"."rep_availability" to "anon";

grant delete on table "public"."rep_availability" to "authenticated";

grant insert on table "public"."rep_availability" to "authenticated";

grant references on table "public"."rep_availability" to "authenticated";

grant select on table "public"."rep_availability" to "authenticated";

grant trigger on table "public"."rep_availability" to "authenticated";

grant truncate on table "public"."rep_availability" to "authenticated";

grant update on table "public"."rep_availability" to "authenticated";

grant delete on table "public"."rep_availability" to "service_role";

grant insert on table "public"."rep_availability" to "service_role";

grant references on table "public"."rep_availability" to "service_role";

grant select on table "public"."rep_availability" to "service_role";

grant trigger on table "public"."rep_availability" to "service_role";

grant truncate on table "public"."rep_availability" to "service_role";

grant update on table "public"."rep_availability" to "service_role";


  create policy "Bookings delete for admin"
  on "public"."bookings"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Bookings select for owner or admin"
  on "public"."bookings"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));



  create policy "Bookings update for owner or admin"
  on "public"."bookings"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))))
with check ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));



  create policy "Rep availability delete for owner or admin"
  on "public"."rep_availability"
  as permissive
  for delete
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));



  create policy "Rep availability insert for owner or admin"
  on "public"."rep_availability"
  as permissive
  for insert
  to authenticated
with check (((sales_id IS NULL) OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid()))) OR public.is_admin()));



  create policy "Rep availability select for owner or admin"
  on "public"."rep_availability"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));



  create policy "Rep availability update for owner or admin"
  on "public"."rep_availability"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))))
with check ((public.is_admin() OR (sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid())))));


CREATE TRIGGER notify_on_booking_created_trigger AFTER INSERT ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.notify_on_booking_created();


