-- Stop-on-reply foundations.
--
-- 1. email_suppressions: the email twin of sms_suppressions. The drip email
--    footer has always promised 'reply "stop" and I won't email again' — this
--    table makes the promise machine-enforced (dispatch_tasks checks it before
--    every email send; quo_inbound STOP, the Gmail reply scan, and the Postmark
--    reply webhook write to it).
-- 2. notifications type 'lead_replied': the human 5-minute-SLA ping fired the
--    moment a lead responds on any channel (SMS / email / phone call).
-- 3. Phone normalization, permanent: every write to contacts.phone_jsonb is
--    normalized to E.164 by a BEFORE trigger, so the CRM UI, CSV imports,
--    Zapier, and edge functions can never re-introduce the digits-only /
--    formatted numbers that fractured identity matching (a reply from such a
--    contact created a duplicate and cancelled nothing).
-- 4. E.164 backfill for existing rows (contacts + sms_suppressions).

-- 1. email_suppressions ------------------------------------------------------
create table if not exists public.email_suppressions (
    id bigint generated by default as identity primary key,
    email text not null,
    reason text not null default 'stop',
    contact_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint email_suppressions_email_unique unique (email)
);

alter table public.email_suppressions
    drop constraint if exists email_suppressions_contact_id_fkey;
alter table public.email_suppressions
    add constraint email_suppressions_contact_id_fkey
    foreign key (contact_id) references public.contacts(id)
    on update cascade on delete set null;

-- Service-role only (same posture as sms_suppressions: RLS on, no policies).
alter table public.email_suppressions enable row level security;

-- 2. notifications: allow the lead_replied type ------------------------------
alter table public.notifications drop constraint notifications_type_check;
alter table public.notifications
    add constraint notifications_type_check check (
      type in ('comment_on_post', 'lead_assigned', 'payout_approved', 'payout_paid', 'booking_created', 'agent_handoff', 'call_due', 'lead_replied')
    );

-- 3. Permanent phone normalization ------------------------------------------
CREATE OR REPLACE FUNCTION "public"."phone_to_e164"("raw" "text") RETURNS "text"
    LANGUAGE "plpgsql" IMMUTABLE
    AS $$
declare
  digits text;
begin
    if raw is null then
        return null;
    end if;
    if left(btrim(raw), 1) = '+' then
        digits := regexp_replace(raw, '\D', '', 'g');
        return case when digits = '' then raw else '+' || digits end;
    end if;
    digits := regexp_replace(raw, '\D', '', 'g');
    if digits = '' then
        return raw;
    elsif length(digits) = 10 then
        return '+1' || digits;
    elsif length(digits) = 11 and left(digits, 1) = '1' then
        return '+' || digits;
    else
        return '+' || digits;
    end if;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."normalize_contact_phones"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
    if new.phone_jsonb is not null and jsonb_typeof(new.phone_jsonb) = 'array' then
        select coalesce(jsonb_agg(
            case
                when jsonb_typeof(elem) = 'object' and (elem->>'number') is not null
                    then jsonb_set(elem, '{number}', to_jsonb(public.phone_to_e164(elem->>'number')))
                when jsonb_typeof(elem) = 'string' and btrim(elem #>> '{}') <> ''
                    then to_jsonb(public.phone_to_e164(elem #>> '{}'))
                else elem
            end
            order by ord
        ), '[]'::jsonb)
        into new.phone_jsonb
        from jsonb_array_elements(new.phone_jsonb) with ordinality as t(elem, ord);
    end if;
    return new;
end;
$$;

-- "05_" so it fires before 10_lowercase_contact_emails / 20_contact_saved
-- (same-event triggers fire in name order).
create or replace trigger "05_normalize_contact_phones"
    before insert or update on public.contacts
    for each row execute function public.normalize_contact_phones();

-- 4. E.164 backfill ----------------------------------------------------------
-- User triggers off for the bulk update: 20_contact_saved makes an HTTP
-- avatar lookup PER ROW (and can stamp avatar='{"src":"ERROR"}' on failure) —
-- a thousand-row backfill must not hammer that. The update itself applies the
-- exact same normalization the new trigger enforces going forward.
alter table public.contacts disable trigger user;

update public.contacts
set phone_jsonb = (
  select coalesce(jsonb_agg(
    case
      when jsonb_typeof(elem) = 'object' and (elem->>'number') is not null
        then jsonb_set(elem, '{number}', to_jsonb(public.phone_to_e164(elem->>'number')))
      when jsonb_typeof(elem) = 'string' and btrim(elem #>> '{}') <> ''
        then to_jsonb(public.phone_to_e164(elem #>> '{}'))
      else elem
    end
    order by ord
  ), '[]'::jsonb)
  from jsonb_array_elements(phone_jsonb) with ordinality as t(elem, ord)
)
where jsonb_typeof(phone_jsonb) = 'array'
  and exists (
    select 1 from jsonb_array_elements(phone_jsonb) as e
    where (jsonb_typeof(e) = 'object'
           and (e->>'number') is not null
           and (e->>'number') is distinct from public.phone_to_e164(e->>'number'))
       or (jsonb_typeof(e) = 'string'
           and btrim(e #>> '{}') <> ''
           and (e #>> '{}') is distinct from public.phone_to_e164(e #>> '{}'))
  );

alter table public.contacts enable trigger user;

-- sms_suppressions: several stored formats can normalize to the SAME number
-- ('3105550000', '1 310 555 0000', '+1 (310) 555-0000'). Keep ONE row per
-- normalized number — prefer an already-normalized row, else the oldest — then
-- normalize the survivors.
delete from public.sms_suppressions s
using public.sms_suppressions o
where s.id <> o.id
  and public.phone_to_e164(s.phone) = public.phone_to_e164(o.phone)
  and (
    (o.phone = public.phone_to_e164(o.phone) and s.phone <> public.phone_to_e164(s.phone))
    or (
      (o.phone = public.phone_to_e164(o.phone)) = (s.phone = public.phone_to_e164(s.phone))
      and o.id < s.id
    )
  );

update public.sms_suppressions
set phone = public.phone_to_e164(phone)
where phone is distinct from public.phone_to_e164(phone);
