-- Robin Line sales-funnel automation.
-- ADDITIVE ONLY: creates 3 new tables and widens one notification type check.
-- Existing tables, columns, functions and data are untouched.
-- Mirrors the declarative additions in schemas/01_tables.sql + 05_policies.sql,
-- so `db diff` stays clean. Apply with `npx supabase db push` (no local stack).

create table public.scheduled_tasks (
    id bigint generated by default as identity primary key,
    deal_id bigint,
    contact_id bigint,
    task_type text not null,
    payload jsonb not null default '{}'::jsonb,
    run_at timestamp with time zone not null,
    status text not null default 'pending',
    attempts smallint not null default 0,
    last_error text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint scheduled_tasks_status_check check (status in ('pending', 'processing', 'sent', 'failed', 'canceled'))
);

create table public.sms_suppressions (
    id bigint generated by default as identity primary key,
    phone text not null,
    reason text not null default 'stop',
    contact_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint sms_suppressions_phone_unique unique (phone)
);

create table public.agent_messages (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    deal_id bigint,
    direction text not null,
    body text not null,
    created_at timestamp with time zone not null default now(),
    constraint agent_messages_direction_check check (direction in ('inbound', 'outbound'))
);

alter table public.scheduled_tasks
    add constraint scheduled_tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.scheduled_tasks
    add constraint scheduled_tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;
alter table public.sms_suppressions
    add constraint sms_suppressions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;
alter table public.agent_messages
    add constraint agent_messages_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;
alter table public.agent_messages
    add constraint agent_messages_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete set null;

create index scheduled_tasks_due_idx on public.scheduled_tasks using btree (run_at) where status = 'pending';
create index scheduled_tasks_deal_id_idx on public.scheduled_tasks using btree (deal_id);
create index scheduled_tasks_contact_id_idx on public.scheduled_tasks using btree (contact_id);
create index agent_messages_contact_id_created_idx on public.agent_messages using btree (contact_id, created_at);

alter table public.scheduled_tasks enable row level security;
alter table public.sms_suppressions enable row level security;
alter table public.agent_messages enable row level security;

-- Widen the notification type check to allow the agent's human-handoff / stalled
-- alerts. (Drop + re-add is the only way to change a CHECK constraint.)
alter table public.notifications drop constraint notifications_type_check;
alter table public.notifications add constraint notifications_type_check
  check (type in ('comment_on_post', 'lead_assigned', 'payout_approved', 'payout_paid', 'booking_created', 'agent_handoff'));
