
  create table "public"."notifications" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "type" text not null,
    "payload" jsonb not null default '{}'::jsonb,
    "read_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."notifications" enable row level security;

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE INDEX notifications_sales_id_created_at_idx ON public.notifications USING btree (sales_id, created_at DESC);

CREATE INDEX notifications_sales_id_unread_idx ON public.notifications USING btree (sales_id, read_at) WHERE (read_at IS NULL);

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."notifications" add constraint "notifications_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_sales_id_fkey";

alter table "public"."notifications" add constraint "notifications_type_check" CHECK ((type = ANY (ARRAY['comment_on_post'::text, 'lead_assigned'::text, 'payout_approved'::text, 'payout_paid'::text]))) not valid;

alter table "public"."notifications" validate constraint "notifications_type_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.notify_on_community_comment()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  post_author_id bigint;
  post_title text;
begin
  select sales_id, title into post_author_id, post_title
  from public.community_posts where id = NEW.post_id;

  if post_author_id is null or post_author_id = NEW.sales_id then
    return NEW;
  end if;

  insert into public.notifications (sales_id, type, payload)
  values (
    post_author_id,
    'comment_on_post',
    jsonb_build_object(
      'post_id', NEW.post_id,
      'post_title', coalesce(post_title, ''),
      'comment_id', NEW.id,
      'commenter_sales_id', NEW.sales_id
    )
  );
  return NEW;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_on_lead_assignment()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if NEW.sales_id is null then
    return NEW;
  end if;
  if TG_OP = 'UPDATE' and OLD.sales_id is not distinct from NEW.sales_id then
    return NEW;
  end if;

  insert into public.notifications (sales_id, type, payload)
  values (
    NEW.sales_id,
    'lead_assigned',
    jsonb_build_object(
      'contact_id', NEW.id,
      'first_name', NEW.first_name,
      'last_name', NEW.last_name
    )
  );
  return NEW;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_on_payout_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  notif_type text;
begin
  if TG_OP <> 'UPDATE' then
    return NEW;
  end if;
  if OLD.status is not distinct from NEW.status then
    return NEW;
  end if;

  if NEW.status = 'approved' then
    notif_type := 'payout_approved';
  elsif NEW.status = 'paid' then
    notif_type := 'payout_paid';
  else
    return NEW;
  end if;

  insert into public.notifications (sales_id, type, payload)
  values (
    NEW.sales_id,
    notif_type,
    jsonb_build_object(
      'payout_id', NEW.id,
      'deal_id', NEW.deal_id,
      'amount_cents', NEW.amount_cents
    )
  );
  return NEW;
end;
$function$
;

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";


  create policy "Notifications delete self"
  on "public"."notifications"
  as permissive
  for delete
  to authenticated
using ((sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid()))));



  create policy "Notifications select self"
  on "public"."notifications"
  as permissive
  for select
  to authenticated
using ((sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid()))));



  create policy "Notifications update self"
  on "public"."notifications"
  as permissive
  for update
  to authenticated
using ((sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid()))))
with check ((sales_id = ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = auth.uid()))));


CREATE TRIGGER notify_on_community_comment_trigger AFTER INSERT ON public.community_comments FOR EACH ROW EXECUTE FUNCTION public.notify_on_community_comment();

CREATE TRIGGER notify_on_lead_assignment_trigger AFTER INSERT OR UPDATE OF sales_id ON public.contacts FOR EACH ROW EXECUTE FUNCTION public.notify_on_lead_assignment();

CREATE TRIGGER notify_on_payout_status_trigger AFTER UPDATE OF status ON public.deal_payouts FOR EACH ROW EXECUTE FUNCTION public.notify_on_payout_status();


